name: Testing

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["3.2", "3.3"]
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev default-libmysqlclient-dev graphviz
      - name: Build and test
        env:
          DATABASE_URL: "postgresql://postgres:postgres@127.0.0.1:5432/postgres"
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          RAILS_ENV: test
        run: |
          bundle exec rake app:wf
          bundle exec rails app:db:create app:db:migrate test
